backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "person"
    label: "Person"
    folder: "src/pages/person"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "person",
        }
      - { label: Name, name: name, widget: string }
      - { label: LinkedIn, name: linkedin, widget: string }
      - { label: Description, name: description, widget: markdown }
      - { label: Title, name: title, widget: string }
      - { label: Founder, name: founder, widget: string }
      - { label: Pic, name: pic, widget: image }
      - {
          label: Boards,
          name: boards,
          widget: list,
          fields:
            [
              { label: Name, name: name, widget: string },
              { label: URL, name: url, widget: string },
              { label: Logo, name: logo, widget: image },
            ],
        }
      - { label: BoardsSubheading, name: boardsSubheading, widget: string }
      - {
          label: Recognitions,
          name: recognitions,
          widget: list,
          fields:
            [
              { label: Name, name: name, widget: string },
              { label: URL, name: url, widget: string },
              { label: Logo, name: logo, widget: image },
            ],
        }
      - {
          label: RecognitionsSubheading,
          name: recognitionsSubheading,
          widget: string,
        }
      - {
          label: Media,
          name: media,
          widget: list,
          fields:
            [
              { label: Name, name: name, widget: string },
              { label: URL, name: url, widget: string },
              { label: Logo, name: logo, widget: image },
            ],
        }
      - { label: mediaSubheading, name: MediaSubheading, widget: string }
      - {
          label: Engagements,
          name: engagements,
          widget: list,
          fields:
            [
              { label: Name, name: name, widget: string },
              { label: URL, name: url, widget: string },
              { label: Logo, name: logo, widget: image },
            ],
        }
      - {
          label: engagementsSubheading,
          name: EngagementsSubheading,
          widget: string,
        }
  - name: "company"
    label: "Company"
    folder: "src/pages/company"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "company",
        }
      - { label: Name, name: name, widget: string }
      - { label: Status, name: status, widget: string }
      - { label: Description, name: description, widget: markdown }
      - { label: Pic, name: pic, widget: image }
      - { label: URL, name: url, widget: string }
      - {
          label: Category,
          name: category,
          widget: select,
          options: ["exited", "founded", "invested"],
        }
  - name: "investor"
    label: "Investor"
    folder: "src/pages/investor"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "investor",
        }
      - { label: Name, name: name, widget: string }
      - { label: Pic, name: pic, widget: image }
      - { label: URL, name: url, widget: string }
  - name: "news"
    label: "news"
    folder: "src/pages/news"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "news",
        }
      - { label: Name, name: name, widget: string }
      - { label: Company, name: company, widget: string }
      - { label: Pic, name: pic, widget: image }
      - { label: URL, name: url, widget: string }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Heading, name: heading, widget: string }
          - { label: CTA, name: cta, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: InvestorsHeading, name: investorsHeading, widget: string }
          - {
              label: InvestorsSubheading,
              name: investorsSubheading,
              widget: string,
            }
          - { label: InvestorsCTA, name: investorsCta, widget: string }
          - {
              label: VCs,
              name: vcs,
              widget: list,
              fields:
                [
                  { label: Name, name: name, widget: string },
                  { label: URL, name: url, widget: string },
                  { label: Logo, name: logo, widget: image },
                ],
            }
          - { label: CompaniesHeading, name: companiesHeading, widget: string }
          - {
              label: CompaniesSubheading,
              name: companiesSubheading,
              widget: string,
            }
          - { label: CompaniesCTA, name: companiesCta, widget: string }
          - {
              label: Companies,
              name: companies,
              widget: list,
              fields:
                [
                  { label: Name, name: name, widget: string },
                  { label: URL, name: url, widget: string },
                  { label: Logo, name: logo, widget: image },
                ],
            }
          - {
              label: Exits,
              name: exits,
              widget: list,
              fields:
                [
                  { label: Name, name: name, widget: string },
                  { label: URL, name: url, widget: string },
                  { label: Logo, name: logo, widget: image },
                ],
            }
          - {
              label: Investments,
              name: investments,
              widget: list,
              fields:
                [
                  { label: Name, name: name, widget: string },
                  { label: URL, name: url, widget: string },
                  { label: Logo, name: logo, widget: image },
                ],
            }
      - file: "src/pages/people/index.md"
        label: "People"
        name: "people"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "people-page",
            }
          - {
              label: people,
              name: people,
              widget: list,
              fields:
                [
                  { label: Name, name: name, widget: string },
                  { label: Title, name: title, widget: string },
                  { label: Founder, name: founder, widget: string },
                  { label: Pic, name: pic, widget: image },
                ],
            }
